addSbtPlugin("com.github.sbt"            % "sbt-ci-release"    % "1.5.11")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"          % "2.3.7")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.5.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"        % "5.9.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github"        % "0.11.8")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-header" % "0.11.8")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-mdoc"   % "0.11.8")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.4.1")
