addSbtPlugin("com.github.sbt"            % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"          % "2.3.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.4.6")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"        % "5.7.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github"        % "0.11.2")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-header" % "0.11.2")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-mdoc"   % "0.11.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.4.1")
